model:
  base_learning_rate: 1.0e-05
  target: zero123plus.model.MVDiffusion
  params:
    drop_cond_prob: 0.1
    precision_half: true

    stable_diffusion_config:
      pretrained_model_name_or_path: sudo-ai/zero123plus-v1.1
      custom_pipeline: ./zero123plus

    use_depth_controlnet: true
    use_seam_loss: true

data:
  target: src.data.objaverse_zero123plus.DataModuleFromConfig
  params:
    batch_size: 2
    num_workers: 0
    train:
      target: src.data.objaverse_zero123plus.ObjaverseData
      params:
        root_dir: /home/sogang/mnt/db_1/jaehoon/objaverse
        meta_fname: lvis-annotations.json
        image_dir: zero123plus-dataset
        validation: false
    validation:
      target: src.data.objaverse_zero123plus.ObjaverseData
      params:
        root_dir: /home/sogang/mnt/db_1/jaehoon/objaverse
        meta_fname: lvis-annotations.json
        image_dir: zero123plus-dataset
        validation: true


lightning:
  modelcheckpoint:
    params:
      every_n_train_steps: 1000
      save_top_k: -1
      save_last: true
  callbacks: {}

  trainer:
    benchmark: true
    max_epochs: 1 #-1
    max_steps: 6
    # detect_anomaly: True
    # profiler: "advanced"
    gradient_clip_val: 1.0
    val_check_interval: 1000
    num_sanity_val_steps: 0
    accumulate_grad_batches: 1
    check_val_every_n_epoch: null   # if not set this, validation does not run
